apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-prod
  namespace: argocd
spec:
  project: banking-prod-project
  
  source:
    repoURL: https://github.com/YonatanDas/Banking-Microservices-Platform.git
    targetRevision: main
    path: monitoring/prometheus-operator
    helm:
      valueFiles:
        - values/prod.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

