apiVersion: v2
name: prometheus-operator
description: Wrapper chart for kube-prometheus-stack
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 55.0.0
    repository: https://prometheus-community.github.io/helm-charts

