version: "3.9"

networks:
  banking-app-net:
    driver: bridge

services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    image: YonatanDas/accounts:v1
    container_name: accounts
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - banking-app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    image: YonatanDas/cards:v1
    container_name: cards
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "9000:9000"
    networks:
      - banking-app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    image: YonatanDas/loans:v1
    container_name: loans
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8090:8090"
    networks:
      - banking-app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  gateway:
    build:
      context: ./gatewayserver
      dockerfile: Dockerfile
    image: YonatanDas/gateway:v1
    container_name: gateway
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8072:8072"
    networks:
      - banking-app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8072/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always