global:
  environment: dev
  aws:
    region: us-east-1
  springProfile: dev
  javaToolOptions: ""
  otelExporterEndpoint: ""
  otelMetricsExporter: none
  otelLogsExporter: none
  
  
  eso:
    enabled: true
    namespace: default
    secretStoreName: aws-secret-store
    service: SecretsManager
    installCRDs: true
  
configMapName: bankingapp-config

# Per-service overrides
accounts:
  serviceAccount:
    name: accounts-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-accounts-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: dev-db-credentials

cards:
  serviceAccount:
    name: cards-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-cards-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: dev-db-credentials

loans:
  serviceAccount:
    name: loans-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-loans-rds-access-role
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: dev-db-credentials

gateway:
  serviceAccount:
    create: true
    name: gateway-sa
  image:
    tag: v1.0.0
  replicaCount: 1
  secretName: dev-db-credentials
  service:
    type: LoadBalancer