apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-dev
  namespace: argocd
spec:
  project: platform-dev-project
  
  source:
    repoURL: https://github.com/YonatanDas/Banking-Microservices-Platform.git
    targetRevision: feature/platform-modularization
    path: monitoring/prometheus-operator
    helm:
      valueFiles:
        - values/dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipCRDs=true
      - ServerSideApply=true
  
  ignoreDifferences:
    - group: ''
      kind: Service
      namespace: kube-system
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com

