apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alerts-dev
  namespace: argocd
spec:
  project: banking-dev-project
  
  source:
    repoURL: https://github.com/YonatanDas/Banking-Microservices-Platform.git
    targetRevision: main
    path: 08-monitoring/prometheus-operator/alerts
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: PrometheusRule
      jsonPointers:
        - /metadata/annotations

