apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.accounts.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.global.eso.secretStoreName | default "aws-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.accounts.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.accounts.secretName }}     
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: password
    - secretKey: HOST
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: dbhost
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.accounts.secretName }}
        property: dbname
